version: '3.8'

services:
  # 모델 미리 다운로드 서비스
  model-downloader:
    image: debian:bookworm-slim
    command: >
      bash -c "
        apt-get update && apt-get install -y curl ;
        mkdir -p ${MODEL_DIR};
        curl -fsSL https://ollama.ai/install.sh | sh ;
        ollama pull ${EMBEDDING_MODEL} --model-path ${MODEL_DIR} ;
        ollama pull ${TTS_MODEL} --model-path ${MODEL_DIR} ;
        ollama pull ${STT_MODEL} --model-path ${MODEL_DIR} ;
        sleep 5
      "
    environment:
      - MODEL_DIR=${MODEL_DIR}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - TTS_MODEL=${TTS_MODEL}
      - STT_MODEL=${STT_MODEL}
    volumes:
      - ${MODEL_DIR}:${MODEL_DIR}

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODELS=/root/.ollama
    depends_on:
      - model-downloader
    volumes:
      - ${MODEL_DIR}:/root/.ollama
    restart: unless-stopped
