version: "3.9"
services:
  model-downloader:
    build: ./model-downloader
    environment:
      - MODEL_DIR=${MODEL_DIR}
    volumes:
      - ${MODEL_DIR}:${MODEL_DIR}
    restart: "no"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODELS=/root/.ollama
    depends_on:
      - model-downloader
    volumes:
      - ${MODEL_DIR}:/root/.ollama
    restart: unless-stopped
