services:

  whisper:
    # ...
    environment:
      - MODEL_DIR=/models
    volumes:
      - ${MODEL_ROOT}/whisper:/models
    command: ["--model", "base", "--model-dir", "/models"]

  kokoro_tts:
    # ...
    environment:
      - MODEL_DIR=/kokoro_models
    volumes:
      - ${MODEL_ROOT}/kokoro:/kokoro_models
    command: ["--model-path", "/kokoro_models"]

  embedding_e5:
    # ...
    environment:
      - MODEL_DIR=/models
    volumes:
      - ${MODEL_ROOT}/e5:/models
    command: ["--model", "intfloat/multilingual-e5-large-instruct", "--model-dir", "/models"]

  ollama:
    # ...
    environment:
      - OLLAMA_MODELS=/root/.ollama
    volumes:
      - ${MODEL_ROOT}/ollama:/root/.ollama
    command: ["ollama", "serve"]
